version: '3.1'

services:
  api:
    build: .
    ports:
      - 8000:8000
    environment:
      - DSN=postgresql://postgres:zxc098cxz@db:5432/app
  db:
    image: pgrouting/pgrouting
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: zxc098cxz
      POSTGRES_DB: app
    volumes:
      - postgres-data:/var/lib/postgresql/data 
  
volumes:
  postgres-data: